### ISSUE TITLE
this is work into apex legends ?

### ISSUE THREAD

**Issue by Exotikcheatt** [WzrterFX/wmemory-read-write-memory#1]

**Comment by WzrterFX** [comment]
Yes, you can read/write the memory of any x64 process

**Comment by Exotikcheatt** [comment]
> Yes, you can read/write the memory of any x64 process

thanks you i try but no success for Read/Write my cheats for apex legends
![Untitled](https://github.com/WzrterFX/wmemory-read-write-memory/assets/151665701/1a9dafd1-6249-40ec-8ac9-c4a485ed1f06)

**Comment by WzrterFX** [comment]
Structure is
```
uintptr_t ReadMemory(HANDLE processHandle, uintptr_t address, size_t size);
```
Your code must like that
```
EntityHead.x = Wmemory::ReadMemory(processHandle, pBoneArray + 0xCC + (BoneId * 0x30), sizeof(float)) + BasePosition.x;
EntityHead.x = Wmemory::ReadMemory(processHandle, pBoneArray + 0xDC + (BoneId * 0x30), sizeof(float)) + BasePosition.y;
EntityHead.x = Wmemory::ReadMemory(processHandle, pBoneArray + 0xEC + (BoneId * 0x30), sizeof(float)) + BasePosition.z;
```

**Comment by WzrterFX** [comment]
I wanted to make an update so that the <T> templates would work and be convenient
I'll do this now

**Comment by Exotikcheatt** [comment]
> I wanted to make an update so that the templates would work and be convenient
> I'll do this now

man that would be great of you thank you very much I'll hear from you right away LOVE YOU <3

**Comment by Exotikcheatt** [comment]
i test your new project 
now i have 0 error ( not testing into game )
https://streamable.com/ihyfi0

**Comment by Exotikcheatt** [comment]
> I finally updated the library, reading records works correctly for me = )

I don't think this is possible on certain games with modern anticheat because I tested and I don't get any base address

**Comment by WzrterFX** [comment]
Does your address work in Cheat Engine? If not, then either you didn’t find it correctly, and try setting “Multi-byte encoding” in the project settings

**Comment by Exotikcheatt** [comment]
> Does your address work in Cheat Engine? If not, then either you didn’t find it correctly, and try setting “Multi-byte encoding” in the project settings
![Untitled](https://github.com/WzrterFX/wmemory-read-write-memory/assets/151665701/6bd60bf3-af02-49af-ba3a-149b5de61c14)

Generaly i take Modebase from function I don't need to use cheat engine
like that

**Comment by WzrterFX** [comment]
Do you have all your memory from .exe?
and the address should look like this r5Apex.exe + ... ?

**Comment by Exotikcheatt** [comment]
> Do you have all your memory from .exe? and the address should look like this r5Apex.exe + ... ?

Yes because generally with a kernel driver I use r5apex.exe (which is the .exe of apex legends) and it works

**Comment by WzrterFX** [comment]
Did you run it as administrator? maybe there is no access

**Comment by Exotikcheatt** [comment]
> Did you run it as administrator? maybe there is no access

of course the software is already in administrator but as I said apex legends has EAC (Easy anti cheat) and I think you really need a kernel driver for it to work

**Comment by WzrterFX** [comment]
it’s external, it doesn’t seem to be detected, at least that’s what I thought
I'll checked EAC this tomorrow

**Comment by Exotikcheatt** [comment]
> it’s external, it doesn’t seem to be detected, at least that’s what I thought I'll checked EAC this tomorrow

perfect than ks you alot

**Comment by Exotikcheatt** [comment]
> it’s external, it doesn’t seem to be detected, at least that’s what I thought I'll checked EAC this tomorrow

had you tested. on apex?
